PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX orbac-owl: <https://raw.githubusercontent.com/bleuontologies/orbac.owl/refs/heads/main/orbac.owl#> # Adjust the base URI as necessary

# query for conflicts
SELECT DISTINCT ?employ ?use ?define ?employBiss ?useBiss ?defineBiss
WHERE {{
    ?employ rdf:type orbac-owl:Employ .
    ?employ orbac-owl:employesEmployee ?s .
    
    ?use rdf:type orbac-owl:Use .
    ?use orbac-owl:usesObject ?o .
    ?use orbac-owl:usesView ?v .
   
    ?consider rdf:type orbac-owl:Consider .
    ?consider orbac-owl:considersAction ?alpha .
    ?consider orbac-owl:considersActivity ?a .
    
    ?define rdf:type orbac-owl:Define .
    ?define orbac-owl:definesSubject ?s .
    ?define orbac-owl:definesAction ?alpha .
    ?define orbac-owl:definesObject ?o .
    ?define orbac-owl:definesContext ?c .

    ?permission rdf:type orbac-owl:Permission .
    ?permission orbac-owl:accessTypeRole ?r .
    ?permission orbac-owl:accessTypeActivity ?a .
    ?permission orbac-owl:accessTypeView ?v .
    ?permission orbac-owl:accessTypeContext ?c .

    {{
    ?employ orbac-owl:employesEmployer ?org .
    }} UNION    {{
    ?employ orbac-owl:employesEmployer ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
    {{
    ?use orbac-owl:usesEmployer ?org .
    }} UNION    {{
    ?use orbac-owl:usesEmployer ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
    {{
    ?consider orbac-owl:considersOrganisation ?org .
    }} UNION    {{
    ?consider orbac-owl:considersOrganisation ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
    {{
    ?define orbac-owl:definesOrganisation ?org .
    }} UNION    {{
    ?define orbac-owl:definesOrganisation ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
    {{
    ?permission orbac-owl:accessTypeOrganisation ?org .
    }} UNION    {{
    ?permission orbac-owl:accessTypeOrganisation ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
    {{
    ?employ orbac-owl:employesRole ?r .
    }} UNION {{
    ?employ orbac-owl:employesRole ?r2 .
    {{?r2 rdf:type orbac-owl:SubRole .}} UNION {{?r2 rdf:type orbac-owl:SeniorRole .}}
    ?r2 orbac-owl:hasParent+ ?r .
    ?r2 orbac-owl:subRoleOrganisation ?org .
    }}

    ?useBiss rdf:type orbac-owl:Use .
    ?useBiss orbac-owl:usesObject ?o .
    ?useBiss orbac-owl:usesView ?vBiss .
   
    ?considerBiss rdf:type orbac-owl:Consider .
    ?considerBiss orbac-owl:considersAction ?alpha .
    ?considerBiss orbac-owl:considersActivity ?aBiss .
    
    ?defineBiss rdf:type orbac-owl:Define .
    ?defineBiss orbac-owl:definesSubject ?s .
    ?defineBiss orbac-owl:definesAction ?alpha .
    ?defineBiss orbac-owl:definesObject ?o .
    ?defineBiss orbac-owl:definesContext ?cBiss .

    ?prohibition rdf:type orbac-owl:Prohibition .
    ?prohibition orbac-owl:accessTypeRole ?rBiss .
    ?prohibition orbac-owl:accessTypeActivity ?aBiss .
    ?prohibition orbac-owl:accessTypeView ?vBiss .
    ?prohibition orbac-owl:accessTypeContext ?cBiss .

    {{
    ?employBiss orbac-owl:employesEmployer ?orgBiss .
    }} UNION    {{
    ?employBiss orbac-owl:employesEmployer ?org2Biss .
    ?orgBiss orbac-owl:subOrganisationOf+ ?org2Biss . 
    }}
    {{
    ?useBiss orbac-owl:usesEmployer ?orgBiss .
    }} UNION    {{
    ?useBiss orbac-owl:usesEmployer ?org2Biss .
    ?orgBiss orbac-owl:subOrganisationOf+ ?org2Biss . 
    }}
    {{
    ?considerBiss orbac-owl:considersOrganisation ?orgBiss .
    }} UNION    {{
    ?considerBiss orbac-owl:considersOrganisation ?org2Biss .
    ?orgBiss orbac-owl:subOrganisationOf+ ?org2Biss . 
    }}
    {{
    ?defineBiss orbac-owl:definesOrganisation ?orgBiss .
    }} UNION    {{
    ?defineBiss orbac-owl:definesOrganisation ?org2Biss .
    ?orgBiss orbac-owl:subOrganisationOf+ ?org2Biss . 
    }}
    {{
    ?prohibition orbac-owl:accessTypeOrganisation ?orgBiss .
    }} UNION    {{
    ?prohibition orbac-owl:accessTypeOrganisation ?org2Biss .
    ?orgBiss orbac-owl:subOrganisationOf+ ?org2Biss . 
    }}
    ?employBiss rdf:type orbac-owl:Employ .
    ?employBiss orbac-owl:employesEmployee ?s .
    {{
    ?employBiss orbac-owl:employesRole ?rBiss .
    }} UNION {{
    ?employBiss orbac-owl:employesRole ?r2Biss .
    {{
    ?r2Biss rdf:type orbac-owl:SubRole .
    ?r2Biss orbac-owl:hasParent+ ?rBiss .
    ?r2Biss orbac-owl:subRoleOrganisation ?orgBiss .
    }} UNION {{
        ?rBiss rdf:type orbac-owl:SeniorRole .
        ?rBiss orbac-owl:hasParent+ ?r2Biss .
        ?rBiss orbac-owl:subRoleOrganisation ?orgBiss .
    }}
    }}
}}