PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX orbac-owl: <https://raw.githubusercontent.com/bleuontologies/orbac.owl/refs/heads/main/orbac.owl#> # Adjust the base URI as necessary
PREFIX : <{example_uri}>

# Obtaining the parameters of a specific definition

SELECT ?org ?subject ?action ?object ?c

WHERE  {{
    
    :{define} rdf:type orbac-owl:Define .
    :{define} orbac-owl:definesSubject ?subject .
    :{define} orbac-owl:definesAction ?action .
    :{define} orbac-owl:definesObject ?object.
    :{define} orbac-owl:definesContext ?c .
    :{define} orbac-owl:definesOrganisation ?org .
}}