PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX orbac-owl: <https://raw.githubusercontent.com/ahmedlaouar/orbac.owl/refs/heads/main/ontology/orbac.owl#> # Adjust the base URI as necessary

SELECT ?perm ?type ?org ?r ?act ?v ?c {{
#    ?perm rdf:type orbac-owl:AccessType .
    ?perm rdf:type ?type .
    FILTER(?type IN (orbac-owl:Permission, orbac-owl:Prohibition, orbac-owl:Obligation))
    ?perm orbac-owl:accessTypeRole ?r .
    ?perm orbac-owl:accessTypeActivity ?act .
    ?perm orbac-owl:accessTypeView ?v .
    ?perm orbac-owl:accessTypeContext ?c .
    {{
    ?perm orbac-owl:accessTypeOrganisation ?org .
#    }} UNION {{
#    ?perm orbac-owl:accessTypeOrganisation ?org2 .
#    ?org orbac-owl:subOrganisationOf* ?org2 . 
    }}
}}