PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <https://raw.githubusercontent.com/bleuontologies/orbac.owl/refs/heads/main/orbac.owl#> # Adjust the base URI as necessary

SELECT ?relation ?org ?s ?alpha ?o ?c {{
    ?relation rdf:type :Define .
    ?relation :definesOrganisation ?org .
    ?relation :definesSubject ?s .
    ?relation :definesAction ?alpha .
    ?relation :definesObject ?o .
    ?relation :definesContext ?c .
}}