PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX orbac-owl: <https://raw.githubusercontent.com/bleuontologies/orbac.owl/refs/heads/main/orbac.owl#> # Adjust the base URI as necessary
PREFIX : <{example_uri}>

# Computing all the individuals involved in the inference of a Permission for a given subject, action, object

SELECT DISTINCT ?permission ?employ ?use ?consider ?define ?v ?a ?c ?r ?org ?org2 
WHERE  {{
    ?employ rdf:type orbac-owl:Employ .
    ?employ orbac-owl:employesEmployee :{subject} .
    
    ?use rdf:type orbac-owl:Use .
    ?use orbac-owl:usesObject :{object}.
    ?use orbac-owl:usesView ?v .
   
    ?consider rdf:type orbac-owl:Consider .
    ?consider orbac-owl:considersAction :{action} .
    ?consider orbac-owl:considersActivity ?a .
    
    ?define rdf:type orbac-owl:Define .
    ?define orbac-owl:definesSubject :{subject} .
    ?define orbac-owl:definesAction :{action} .
    ?define orbac-owl:definesObject :{object}.
    ?define orbac-owl:definesContext ?c .

    {{?permission rdf:type orbac-owl:Permission .}} UNION {{?permission rdf:type orbac-owl:Obligation .}}
    ?permission orbac-owl:accessTypeRole ?r .
    ?permission orbac-owl:accessTypeActivity ?a .
    ?permission orbac-owl:accessTypeView ?v .
    ?permission orbac-owl:accessTypeContext ?c .

     {{
    ?employ orbac-owl:employesEmployer ?org .
    }} UNION     {{
    ?employ orbac-owl:employesEmployer ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
     {{
    ?use orbac-owl:usesEmployer ?org .
    }} UNION     {{
    ?use orbac-owl:usesEmployer ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
     {{
    ?consider orbac-owl:considersOrganisation ?org .
    }} UNION     {{
    ?consider orbac-owl:considersOrganisation ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
     {{
    ?define orbac-owl:definesOrganisation ?org .
    }} UNION     {{
    ?define orbac-owl:definesOrganisation ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
     {{
    ?permission orbac-owl:accessTypeOrganisation ?org .
    }} UNION     {{
    ?permission orbac-owl:accessTypeOrganisation ?org2 .
    ?org orbac-owl:subOrganisationOf+ ?org2 . 
    }}
    ?employ orbac-owl:employesRole ?r .
}}