PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.co-ode.org/ontologies/ont.owl#> # Adjust the base URI as necessary

ASK {{
    ?employ rdf:type :Employ .
    ?employ :employesEmployee :{subject} .
    {{
    ?employ :employesEmployer ?org .
    }} UNION     {{
    ?employ :employesEmployer ?org2 .
    ?org :subOrganisationOf* ?org2 . 
    }}
    {{
    ?employ :employesRole ?r .
    }} UNION  {{
    ?employ :employesRole ?r2 .
     {{?r2 rdf:type :SubRole .}} UNION  {{?r2 rdf:type :SeniorRole .}}
    ?r2 :hasParent+ ?r .
    ?r2 :subRoleOrganisation ?org .
    }}
    
    ?use rdf:type :Use .
    ?use :usesObject :{object}.
    ?use :usesView ?v .
    {{
    ?use :usesEmployer ?org .
    }} UNION     {{
    ?use :usesEmployer ?org2 .
    ?org :subOrganisationOf* ?org2 . 
    }}
    
    ?consider rdf:type :Consider .
    ?consider :considersAction :{action} .
    ?consider :considersActivity ?a .
    {{
    ?consider :considersOrganisation ?org .
    }} UNION     {{
    ?consider :considersOrganisation ?org2 .
    ?org :subOrganisationOf* ?org2 . 
    }}
    
    ?define rdf:type :Define .
    ?define :definesSubject :{subject} .
    ?define :definesAction :{action} .
    ?define :definesObject :{object}.
    ?define :definesContext ?c .
    {{
    ?define :definesOrganisation ?org .
    }} UNION     {{
    ?define :definesOrganisation ?org2 .
    ?org :subOrganisationOf* ?org2 . 
    }}
    
    {{?permission rdf:type :Permission .}} UNION {{?permission rdf:type :Obligation .}}
    ?permission :accessTypeRole ?r .
    ?permission :accessTypeActivity ?a .
    ?permission :accessTypeView ?v .
    ?permission :accessTypeContext ?c .
    {{
    ?permission :accessTypeOrganisation ?org .
    }} UNION     {{
    ?permission :accessTypeOrganisation ?org2 .
    ?org :subOrganisationOf* ?org2 . 
    }}
}}
