PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://www.co-ode.org/ontologies/ont.owl#> # Adjust the base URI as necessary

# Computing supports of a Permission for a given subject, action, object

SELECT ?object ?view ?org

WHERE  {    
    :{use} rdf:type :Use .
    :{use} :usesObject ?object.
    :{use} :usesView ?view .
    :{use} :usesEmployer ?org .
}